<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N700278" name="TestCase.CLtesting.US458CheckShipmentAlreadyLoadedOnTrailer" tests="1" failures="0" timestamp="16 Aug 2016 21:56:39 GMT" time="23.118" errors="1">
  <testcase name="CheckShipmentAlreadyLoadedOnCLHasPro" time="23.118" classname="TestCase.CLtesting.US458CheckShipmentAlreadyLoadedOnTrailer">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: CheckShipmentAlreadyLoadedOnCLHasPro([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)890,(java.lang.String)C890,(java.lang.String)452105,(java.lang.String)J2I8GU9UJ,(java.lang.String)TRAP,(java.lang.String)2,(java.lang.String)2140,(java.sql.Timestamp)2016-08-17 00:00:00.0,(java.sql.Timestamp)2016-08-15 20:27:16.0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: CheckShipmentAlreadyLoadedOnCLHasPro([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)890,(java.lang.String)C890,(java.lang.String)452105,(java.lang.String)J2I8GU9UJ,(java.lang.String)TRAP,(java.lang.String)2,(java.lang.String)2140,(java.sql.Timestamp)2016-08-17 00:00:00.0,(java.sql.Timestamp)2016-08-15 20:27:16.0]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1228)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1125)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- CheckShipmentAlreadyLoadedOnCLHasPro -->
</testsuite> <!-- TestCase.CLtesting.US458CheckShipmentAlreadyLoadedOnTrailer -->
