<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N700278" name="LdgScreen.LDGTesting" tests="10" failures="3" timestamp="26 May 2016 15:29:15 GMT" time="238.441" errors="0">
  <testcase name="SetTrailerToLDGWithProAndLeaveOn" time="25.138" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLDGWithProAndCombineHandle" time="29.244" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLDGWithProAndALLSHORT" time="23.900" classname="LdgScreen.LDGTesting"/>
  <testcase name="LDGWithProChangeCube" time="14.927" classname="LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	shipcount is wrong expected [2] but found [3],
	ship weight is wrong expected [784] but found [1133]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	shipcount is wrong expected [2] but found [3],
	ship weight is wrong expected [784] but found [1133]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at LdgScreen.LDGTesting.LDGWithProChangeCube(LDGTesting.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- LDGWithProChangeCube -->
  <testcase name="LDGWithoutProChangeDestination" time="13.112" classname="LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [MUYR27B0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at LdgScreen.LDGTesting.LDGWithoutProChangeDestination(LDGTesting.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- LDGWithoutProChangeDestination -->
  <testcase name="SetTrailerToLDGWithProAndDock" time="21.505" classname="LdgScreen.LDGTesting"/>
  <testcase name="LDGTrailerWithProChangeDestination" time="16.681" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLoadingNoShipments" time="41.839" classname="LdgScreen.LDGTesting"/>
  <testcase name="NoLdgEmptyTrailerAddNonExistingPro" time="22.935" classname="LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [E888CCO]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [E888CCO]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at LdgScreen.LDGTesting.NoLdgEmptyTrailerAddNonExistingPro(LDGTesting.java:1050)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- NoLdgEmptyTrailerAddNonExistingPro -->
  <testcase name="SetTrailerToLDGWithProAndHeadLoad" time="29.160" classname="LdgScreen.LDGTesting"/>
</testsuite> <!-- LdgScreen.LDGTesting -->
