<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N700278" name="LdgScreen.LDGTesting" tests="10" failures="2" timestamp="16 Jun 2016 08:02:14 GMT" time="273.376" errors="0">
  <testcase name="SetTrailerToLDGWithProAndHeadLoad" time="39.593" classname="LdgScreen.LDGTesting"/>
  <testcase name="NoLdgEmptyTrailerAddNonExistingPro" time="28.267" classname="LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [455]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [455]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at LdgScreen.LDGTesting.NoLdgEmptyTrailerAddNonExistingPro(LDGTesting.java:1038)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- NoLdgEmptyTrailerAddNonExistingPro -->
  <testcase name="SetTrailerToLDGWithProAndALLSHORT" time="22.268" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLDGWithProAndLeaveOn" time="25.263" classname="LdgScreen.LDGTesting"/>
  <testcase name="LDGWithoutProChangeDestination" time="13.885" classname="LdgScreen.LDGTesting">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [326]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	eqps Mainframe_User_ID is wrong expected [UYR27B0] but found [null],
	 eqp Mainframe_User_ID is wrong expected [UYR27B0] but found [326]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at LdgScreen.LDGTesting.LDGWithoutProChangeDestination(LDGTesting.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- LDGWithoutProChangeDestination -->
  <testcase name="LDGTrailerWithProChangeDestination" time="21.087" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLoadingNoShipments" time="40.013" classname="LdgScreen.LDGTesting"/>
  <testcase name="LDGWithProChangeCube" time="17.939" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLDGWithProAndCombineHandle" time="45.529" classname="LdgScreen.LDGTesting"/>
  <testcase name="SetTrailerToLDGWithProAndDock" time="19.532" classname="LdgScreen.LDGTesting"/>
</testsuite> <!-- LdgScreen.LDGTesting -->
